yande-gpt-api
VycheslavRussu/legal-check-ai pull request #1
Opened 2024-05-17 14:39 UTC by VycheslavRussu

Файл с API до Yandex GPT, который позволяет отправлять запросы на модель и получать ответы от нее. Хранит историю запросов внутри себя.

2024-05-17 15:11 UTC, sedirov07 requested changes
Внести изменения, указанные в комментариях к файлу yandex-gpt-api.py построчно

2024-05-17 15:11 UTC, sedirov07 commented on yandex-gpt-api.py
> +    def setup_context(self):
Вместо метода setup_context добавить в методе __init__ вызов self.context_storage.set_default_context(self.setup_messages)

2024-05-17 15:11 UTC, sedirov07 commented on yandex-gpt-api.py
> +        self.__FOLDER_ID = folder_id
Убрать передачу параметров в метод __init__

2024-05-17 19:52 UTC, VycheslavRussu commented on yandex-gpt-api.py
> +    def setup_context(self):
Пофиксил

2024-05-17 19:52 UTC, VycheslavRussu commented on yandex-gpt-api.py
> +        self.__FOLDER_ID = folder_id
Исправил

2024-05-18 07:18 UTC, Airmareing requested changes
см комментарий об оформлении примера

2024-05-18 07:18 UTC, Airmareing commented on models_api/yandex_gpt/yandex_gpt_api.py
> +# # Создали экземпляр класса
Необходимо оформить пример как unit-тест в отдельном файле

2024-05-18 07:43 UTC, sedirov07 approved these changes

2024-05-18 10:37 UTC, VycheslavRussu commented on models_api/yandex_gpt/yandex_gpt_api.py
> +# # Создали экземпляр класса
Ок, вынесу и добавлю в файл с тестами, когда создадим его

2024-05-18 10:37 UTC, VycheslavRussu commented on models_api/yandex_gpt/yandex_gpt_api.py
> +# # Создали экземпляр класса
Сейчас просто уберу из кода

2024-05-18 11:22 UTC, Airmareing approved these changes

2024-05-18 11:41 UTC, merged